### ISSUE TITLE
pget-to-local/mirror-to-local doesn't autostart until processes are stopped/closed

### ISSUE THREAD

**Issue by patrickisfrench** [userdocs/LFTP4WIN-CORE#6] opened 2021-12-28 04:54 UTC
Someone posted about this symptom a year ago without much info: https://github.com/userdocs/LFTP4WIN-CORE/issues/3
I have more information about it though. Seems to only happen when using FTPS(21) rather than SFTP(22). You can also seem to start the download by ctrl+c which will close a process that starts at the beginning of pget-to-local, the /.ssh/known_hosts script? if i try to close the window these processes listed will alert that they are going to stop (see https://i.imgur.com/Hl1MFFb.jpg)
Once clicking OK, the task will start, all 5 parallel segments launch and download properly, everything works as normal. However just sending a file to pget or mirror to local will show an empty mintyy/conemu window (with no progress, blank, black terminal unless one action of ctrl+c is executed or, X the window and clicking okay to stop those processes.
it may be trying to authenticate the transfer assuming there's an SSH key and this halts the download from starting since it's FTPS and doesn't use the same key? I need to use FTPS over SFTP for bandwidth purposes. So If someone can help me prevent this behavior and have files start up automatically without me having to kill these processes each time, would be awesome!

p.s. please explain it like i'm 5 - i really don't have programming experience at all, just pieced this together with some troubleshooting. i may be way off

**Comment by userdocs** [comment] 2021-12-31 01:29
I think you narrowed it down pretty well but i'm not sure why it stalls for you.

I pushed a change i think fixes it so if you update and try again it should be fixed.

**Comment by patrickisfrench** [comment] 2021-12-31 03:04
Hi @userdocs - do you recommend I update using the script or just redownload the latest code as zip?

**Comment by userdocs** [comment] 2021-12-31 03:07
using the update script.

**Comment by patrickisfrench** [comment] 2021-12-31 03:07
verified that worked! appreciate the quick patch! thank you very much! Happy new year!

**Comment by userdocs** [comment] 2021-12-31 12:02
And to you.

If the issue is resolved you can close the issue.

**Closed as completed** 2021-12-31 14:47 UTC
